server:
  port: 8502


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice-app
    username: root
    password: microservice-app
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: ticket-service

spcloud:
  eureka:
    client:
      instance:
        hostname: localhost
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/